/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import customContentManager3 from "../../src/plugins/custom-content-manager3/./dist/admin/index.mjs";
import membershipList from "../../src/plugins/membership-list/./dist/admin/index.mjs";
import testerPlugin from "../../src/plugins/tester-plugin/./dist/admin/index.mjs";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "custom-content-manager3": customContentManager3,
    "membership-list": membershipList,
    "tester-plugin": testerPlugin,
  },
});
